# This file was generated by GoReleaser. DO NOT EDIT.
cask "partyline" do
  binary "partyline", target: "ptln"

  version "0.5.4"

  on_macos do
    on_intel do
      sha256 "d5b058f89197ec4302b89bd67ce79a386535bc132dc1dab53e0a74f746d490e7"
      url "https://github.com/partyline-sh/cli/releases/download/v#{version}/partyline_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "004a45d494e3b03060b24d34718e3d7a1e9b879e6c0db77398742ad306bf8912"
      url "https://github.com/partyline-sh/cli/releases/download/v#{version}/partyline_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bc72f7d08e0b9a5852101ce83bc0624adced91c36e882033b70511ba48fd7939"
      url "https://github.com/partyline-sh/cli/releases/download/v#{version}/partyline_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b55ea9585c840fd74984959af70e0b079e31f94f7c8324d49f894474d0a049b9"
      url "https://github.com/partyline-sh/cli/releases/download/v#{version}/partyline_#{version}_linux_arm64.tar.gz"
    end
  end

  name "partyline"
  desc "One shared terminal, everyone on the line — multiplayer, encrypted terminal sessions for humans and AI agents."
  homepage "https://partyline.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "partyline"

  # No zap stanza required

end
