# This file was generated by GoReleaser. DO NOT EDIT.
cask "partyline" do
  binary "partyline", target: "ptln"
  manpage "partyline.1"
  manpage "ptln.1"

  version "0.6.7"

  on_macos do
    on_intel do
      sha256 "7c48b5d84406183d7db04a85260d938b6b654fc17fa6b9621bf1ca9c10ebc8ca"
      url "https://github.com/partyline-sh/cli/releases/download/v#{version}/partyline_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b103c0d795e4ec7439a32be4c91650eb5ba65cc1c14ec83ca767d1e80ad6399e"
      url "https://github.com/partyline-sh/cli/releases/download/v#{version}/partyline_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "aa382a0c49d84eaa67c5e18ba9174f90e43a33878b26ba4242ed028a82b23808"
      url "https://github.com/partyline-sh/cli/releases/download/v#{version}/partyline_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a4b877fea649b4940f441ff07eb2441632cff5114c9591a3552ff01a8f0d9489"
      url "https://github.com/partyline-sh/cli/releases/download/v#{version}/partyline_#{version}_linux_arm64.tar.gz"
    end
  end

  name "partyline"
  desc "One shared terminal, everyone on the line — multiplayer, encrypted terminal sessions for humans and AI agents."
  homepage "https://partyline.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "partyline"

  # No zap stanza required

end
