# This file was generated by GoReleaser. DO NOT EDIT.
cask "partyline" do
  binary "partyline", target: "ptln"

  version "0.2.6"

  on_macos do
    on_intel do
      sha256 "b1c685a41007682f824a5e5c87c4158e6abb55a8175c85651241aaeeb53b75b5"
      url "https://github.com/partyline-sh/cli/releases/download/v#{version}/partyline_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5b0ac0559f27b797d116327b0b77d662f6df9e31650a03b4248b9bf30f31e38c"
      url "https://github.com/partyline-sh/cli/releases/download/v#{version}/partyline_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bbb7c2c04900c0ac161c2d305bc45a6661be2432265018d13439d9a9fc998ccf"
      url "https://github.com/partyline-sh/cli/releases/download/v#{version}/partyline_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c6120015c9bddc3bbe525a604b49a1b3cb96c7f6597cf2a4666079b17adb1d8b"
      url "https://github.com/partyline-sh/cli/releases/download/v#{version}/partyline_#{version}_linux_arm64.tar.gz"
    end
  end

  name "partyline"
  desc "One shared terminal, everyone on the line — multiplayer, encrypted terminal sessions for humans and AI agents."
  homepage "https://partyline.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "partyline"

  # No zap stanza required

end
